import type { PokemonType } from "./types";

export const TYPE_COLORS: Record<PokemonType, { bg: string; text: string; gradient: string; hex: string; lightHex: string }> = {
  FIRE: {
    bg: "bg-orange-500",
    text: "text-orange-500",
    gradient: "from-orange-500 to-amber-400",
    hex: "#f97316",
    lightHex: "#ffa700",
  },
  WATER: {
    bg: "bg-blue-500",
    text: "text-blue-500",
    gradient: "from-blue-500 to-cyan-400",
    hex: "#3b82f6",
    lightHex: "#67e8f9",
  },
  GRASS: {
    bg: "bg-green-500",
    text: "text-green-500",
    gradient: "from-green-500 to-emerald-400",
    hex: "#22c55e",
    lightHex: "#86efac",
  },
  ELECTRIC: {
    bg: "bg-yellow-400",
    text: "text-yellow-400",
    gradient: "from-yellow-400 to-amber-300",
    hex: "#facc15",
    lightHex: "#fde68a",
  },
  ICE: {
    bg: "bg-cyan-300",
    text: "text-cyan-300",
    gradient: "from-cyan-400 to-sky-300",
    hex: "#67e8f9",
    lightHex: "#a5f3fc",
  },
  FIGHTING: {
    bg: "bg-red-700",
    text: "text-red-700",
    gradient: "from-red-700 to-red-500",
    hex: "#b91c1c",
    lightHex: "#ef4444",
  },
  POISON: {
    bg: "bg-purple-600",
    text: "text-purple-600",
    gradient: "from-purple-600 to-violet-500",
    hex: "#9333ea",
    lightHex: "#c084fc",
  },
  GROUND: {
    bg: "bg-yellow-700",
    text: "text-yellow-700",
    gradient: "from-yellow-700 to-amber-500",
    hex: "#a16207",
    lightHex: "#d97706",
  },
  FLYING: {
    bg: "bg-indigo-400",
    text: "text-indigo-400",
    gradient: "from-indigo-400 to-sky-300",
    hex: "#818cf8",
    lightHex: "#c7d2fe",
  },
  PSYCHIC: {
    bg: "bg-pink-500",
    text: "text-pink-500",
    gradient: "from-pink-500 to-rose-400",
    hex: "#ec4899",
    lightHex: "#f9a8d4",
  },
  BUG: {
    bg: "bg-lime-600",
    text: "text-lime-600",
    gradient: "from-lime-600 to-green-500",
    hex: "#65a30d",
    lightHex: "#a3e635",
  },
  ROCK: {
    bg: "bg-stone-500",
    text: "text-stone-500",
    gradient: "from-stone-500 to-stone-400",
    hex: "#78716c",
    lightHex: "#a8a29e",
  },
  GHOST: {
    bg: "bg-violet-800",
    text: "text-violet-800",
    gradient: "from-violet-800 to-purple-600",
    hex: "#5b21b6",
    lightHex: "#8b5cf6",
  },
  DRAGON: {
    bg: "bg-indigo-700",
    text: "text-indigo-700",
    gradient: "from-indigo-700 to-blue-600",
    hex: "#4338ca",
    lightHex: "#6366f1",
  },
  DARK: {
    bg: "bg-gray-800",
    text: "text-gray-800",
    gradient: "from-gray-800 to-gray-600",
    hex: "#1f2937",
    lightHex: "#4b5563",
  },
  STEEL: {
    bg: "bg-slate-400",
    text: "text-slate-400",
    gradient: "from-slate-400 to-slate-300",
    hex: "#94a3b8",
    lightHex: "#cbd5e1",
  },
  FAIRY: {
    bg: "bg-pink-300",
    text: "text-pink-300",
    gradient: "from-pink-300 to-rose-200",
    hex: "#f9a8d4",
    lightHex: "#fce7f3",
  },
  NORMAL: {
    bg: "bg-gray-400",
    text: "text-gray-400",
    gradient: "from-gray-400 to-gray-300",
    hex: "#9ca3af",
    lightHex: "#d1d5db",
  },
};

export const TYPE_EMOJI: Record<PokemonType, string> = {
  FIRE: "🔥",
  WATER: "💧",
  GRASS: "🌿",
  ELECTRIC: "⚡",
  ICE: "❄️",
  FIGHTING: "👊",
  POISON: "☠️",
  GROUND: "🏔️",
  FLYING: "🌬️",
  PSYCHIC: "🔮",
  BUG: "🐛",
  ROCK: "🪨",
  GHOST: "👻",
  DRAGON: "🐉",
  DARK: "🌑",
  STEEL: "⚙️",
  FAIRY: "✨",
  NORMAL: "⭐",
};

// Type effectiveness chart
export const TYPE_EFFECTIVENESS: Record<PokemonType, { weakTo: PokemonType[]; resistantTo: PokemonType[] }> = {
  FIRE: { weakTo: ["WATER", "ROCK", "GROUND"], resistantTo: ["FIRE", "GRASS", "ICE", "BUG", "STEEL", "FAIRY"] },
  WATER: { weakTo: ["ELECTRIC", "GRASS"], resistantTo: ["FIRE", "WATER", "ICE", "STEEL"] },
  GRASS: { weakTo: ["FIRE", "ICE", "POISON", "FLYING", "BUG"], resistantTo: ["WATER", "ELECTRIC", "GRASS", "GROUND"] },
  ELECTRIC: { weakTo: ["GROUND"], resistantTo: ["ELECTRIC", "FLYING", "STEEL"] },
  ICE: { weakTo: ["FIRE", "FIGHTING", "ROCK", "STEEL"], resistantTo: ["ICE"] },
  FIGHTING: { weakTo: ["FLYING", "PSYCHIC", "FAIRY"], resistantTo: ["BUG", "ROCK", "DARK"] },
  POISON: { weakTo: ["GROUND", "PSYCHIC"], resistantTo: ["GRASS", "FIGHTING", "POISON", "BUG", "FAIRY"] },
  GROUND: { weakTo: ["WATER", "GRASS", "ICE"], resistantTo: ["POISON", "ROCK"] },
  FLYING: { weakTo: ["ELECTRIC", "ICE", "ROCK"], resistantTo: ["GRASS", "FIGHTING", "BUG"] },
  PSYCHIC: { weakTo: ["BUG", "GHOST", "DARK"], resistantTo: ["FIGHTING", "PSYCHIC"] },
  BUG: { weakTo: ["FIRE", "FLYING", "ROCK"], resistantTo: ["GRASS", "FIGHTING", "GROUND"] },
  ROCK: { weakTo: ["WATER", "GRASS", "FIGHTING", "GROUND", "STEEL"], resistantTo: ["NORMAL", "FIRE", "POISON", "FLYING"] },
  GHOST: { weakTo: ["GHOST", "DARK"], resistantTo: ["POISON", "BUG"] },
  DRAGON: { weakTo: ["ICE", "DRAGON", "FAIRY"], resistantTo: ["FIRE", "WATER", "ELECTRIC", "GRASS"] },
  DARK: { weakTo: ["FIGHTING", "BUG", "FAIRY"], resistantTo: ["GHOST", "DARK"] },
  STEEL: { weakTo: ["FIRE", "FIGHTING", "GROUND"], resistantTo: ["NORMAL", "GRASS", "ICE", "FLYING", "PSYCHIC", "BUG", "ROCK", "DRAGON", "STEEL", "FAIRY"] },
  FAIRY: { weakTo: ["POISON", "STEEL"], resistantTo: ["FIGHTING", "BUG", "DARK"] },
  NORMAL: { weakTo: ["FIGHTING"], resistantTo: [] },
};
